# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'javaUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1166, 571)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Bg = QtWidgets.QLabel(self.centralwidget)
        self.Bg.setGeometry(QtCore.QRect(0, -30, 1321, 771))
        self.Bg.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.Bg.setText("")
        self.Bg.setObjectName("Bg")
        self.Bg_Border = QtWidgets.QLabel(self.centralwidget)
        self.Bg_Border.setGeometry(QtCore.QRect(0, 0, 1171, 571))
        self.Bg_Border.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);\n"
"border: 5px Solid White")
        self.Bg_Border.setText("")
        self.Bg_Border.setPixmap(QtGui.QPixmap("background.jpg"))
        self.Bg_Border.setScaledContents(True)
        self.Bg_Border.setObjectName("Bg_Border")
        self.gif1 = QtWidgets.QLabel(self.centralwidget)
        self.gif1.setGeometry(QtCore.QRect(380, 40, 451, 341))
        self.gif1.setStyleSheet("\n"
"")
        self.gif1.setText("")
        self.gif1.setPixmap(QtGui.QPixmap("animation.gif"))
        self.gif1.setScaledContents(True)
        self.gif1.setObjectName("gif1")
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(430, 410, 161, 51))
        self.start.setStyleSheet("")
        self.start.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.start.setIcon(icon)
        self.start.setIconSize(QtCore.QSize(160, 80))
        self.start.setObjectName("start")
        self.stop = QtWidgets.QPushButton(self.centralwidget)
        self.stop.setGeometry(QtCore.QRect(630, 410, 161, 51))
        self.stop.setStyleSheet("")
        self.stop.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Quit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stop.setIcon(icon1)
        self.stop.setIconSize(QtCore.QSize(160, 80))
        self.stop.setObjectName("stop")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(912, 25, 241, 62))
        self.textBrowser.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 75 italic 14pt \"Rockwell\";\n"
"color: rgb(255, 255, 255);")
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 450, 221, 91))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("sounds.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
